### ISSUE TITLE
get_random_ua() raises indexError

### ISSUE THREAD

**Issue by slenderq** [dtaivpp/NewsTicker#1]
Ended up borrowing this function in my own project and found that when:
`len(user_agents) == random_num`, an index error is raised.
Seems like a pretty rare case with the huge list but it can happen!

The function just needs to be changed to:
```
def get_random_ua():
    '''Return Random UserAgent'''
    random_num = random.randint(0, len(user_agents) - 1)
    return user_agents[random_num] ```

**Comment by dtaivpp** [comment]
Thanks for contributing! Fixed in commit #25a30e4
